// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ5BXhoL_l9b8XgHVnRY_lR3ZjgDA4Hp0',
    appId: '1:417997922585:web:c5896c5ebe69ad8d642588',
    messagingSenderId: '417997922585',
    projectId: 'e-commerce-414b9',
    authDomain: 'e-commerce-414b9.firebaseapp.com',
    databaseURL: 'https://e-commerce-414b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-414b9.appspot.com',
    measurementId: 'G-RFB2QRHQ2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ioGUw-_CR_4WkONt3QrIpEB1w7z4YOU',
    appId: '1:417997922585:android:c5a8aa50fabf6c18642588',
    messagingSenderId: '417997922585',
    projectId: 'e-commerce-414b9',
    databaseURL: 'https://e-commerce-414b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-414b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmZAh8dufe7723eo54e8bpWpWmrEXN9fw',
    appId: '1:417997922585:ios:55c9b5c327f8dab7642588',
    messagingSenderId: '417997922585',
    projectId: 'e-commerce-414b9',
    databaseURL: 'https://e-commerce-414b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-414b9.appspot.com',
    androidClientId: '417997922585-uloq88dhe89v35kf693n48f3gb10tiji.apps.googleusercontent.com',
    iosClientId: '417997922585-7dp6gkqbj1p82k282dhnau45pmbr7hcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmZAh8dufe7723eo54e8bpWpWmrEXN9fw',
    appId: '1:417997922585:ios:55c9b5c327f8dab7642588',
    messagingSenderId: '417997922585',
    projectId: 'e-commerce-414b9',
    databaseURL: 'https://e-commerce-414b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-414b9.appspot.com',
    androidClientId: '417997922585-uloq88dhe89v35kf693n48f3gb10tiji.apps.googleusercontent.com',
    iosClientId: '417997922585-7dp6gkqbj1p82k282dhnau45pmbr7hcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ5BXhoL_l9b8XgHVnRY_lR3ZjgDA4Hp0',
    appId: '1:417997922585:web:4f15dc69e6c81517642588',
    messagingSenderId: '417997922585',
    projectId: 'e-commerce-414b9',
    authDomain: 'e-commerce-414b9.firebaseapp.com',
    databaseURL: 'https://e-commerce-414b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-414b9.appspot.com',
    measurementId: 'G-D4TFVM0BDG',
  );

}